AspnetIdentitySample/Controllers/MonitorBeurtController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Examonitor.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;
using System.Data.Entity.Core;
using System.Data.Entity.Core.Objects;
using System.IO;
using System.Data.Entity.Validation;
using System.Diagnostics;
using Newtonsoft.Json;
using Daishi.JsonParser;
using Examonitor.Utility;

namespace Examonitor.Controllers
{
    public class MonitorBeurtController : Controller
    {
        public UserManager<MyUser> UserManager { get; private set; }
        public RoleManager<IdentityRole> RoleManager { get; private set; }
        public MyDbContext db { get; private set; }
        public string MonitorBeurtCampuss { get; set; }

        public MonitorBeurtController()
        {
            db = new MyDbContext();
            UserManager = new UserManager<MyUser>(new UserStore<MyUser>(db));
            RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
        }

        [Authorize]
        // GET: /MonitorBeurt/
        public async Task<ActionResult> Index(string MonitorBeurtCampus, string sortOrder, string currentFilter)
        {
   
            if (MonitorBeurtCampus == null)
                MonitorBeurtCampus = currentFilter;
           ViewBag.CurrentFilter = MonitorBeurtCampus;
            
            
            var currentUser = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var reservatie = from m in db.Reservatie
                             select m;
            //if (!User.IsInRole("Admin"))
         //   {
                reservatie = reservatie.Where(x => x.UserName == currentUser.UserName);
         //   }

            var reservatiesUser = reservatie.ToList();


            var MonitorBeurten = from m in db.MonitorBeurt
                         select m;
            ViewBag.DatumSortParm = String.IsNullOrEmpty(sortOrder) ? "Datum_desc" : "";
            ViewBag.ExamenNaamSortParm = sortOrder == "ExamenNaam" ? "ExamenNaam_desc" : "ExamenNaam";
            ViewBag.CampusSortParm = sortOrder == "Campus" ? "Campus_desc" : "Campus";
            
            switch (sortOrder)
            {
                case "Datum_desc":
                    MonitorBeurten = MonitorBeurten.OrderByDescending(s => s.BeginDatum);
                    break;
                case "Campus":
                    MonitorBeurten = MonitorBeurten.OrderBy(s => s.Campus.Name);
                    break;
                case "Campus_desc":
                    MonitorBeurten = MonitorBeurten.OrderByDescending(s => s.Campus.Name);
                    break;
                case "ExamenNaam":
                    MonitorBeurten = MonitorBeurten.OrderBy(s => s.ExamenNaam);
                    break;
                case "ExamenNaam_desc":
                    MonitorBeurten = MonitorBeurten.OrderByDescending(s => s.ExamenNaam);
                    break;
                default:
                    MonitorBeurten = MonitorBeurten.OrderBy(s => s.BeginDatum);
                    break;
            }
            
            if (!string.IsNullOrEmpty(MonitorBeurtCampus))
            {
                MonitorBeurten = MonitorBeurten.Where(x => x.Campus.Name.ToUpper().Contains(MonitorBeurtCampus.ToUpper()));
               
            }
            foreach (var mb in MonitorBeurten)
            {
                mb.ReservedByCurrentUser = false;
                mb.Available = true;
                if (mb.Capaciteit == mb.Gereserveerd)
                    mb.Available = false;
                mb.Duurtijd = mb.EindDatum.Subtract(mb.BeginDatum).ToString();
                foreach (var rt in reservatiesUser)
                {
                    if (mb.MonitorBeurtId == rt.Toezichtbeurt.MonitorBeurtId)
                    { 
                        mb.ReservedByCurrentUser = true;
                        mb.CurrentRegistratieID = rt.ReservatieId;
                    }
                }
            }
            return View(MonitorBeurten);
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Import()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Import(HttpPostedFileBase file)
        {
            var campusLijst = new List<Campus>();
            IQueryable<Campus> campusQuery = null;
            if(ModelState.IsValid && file != null)
            {
                var monitorbeurtenParsed = new MonitorbeurtParser(file.InputStream, @"monitorbeurt");
                monitorbeurtenParsed.Parse();
                foreach(var monitorbeurt in monitorbeurtenParsed.Result)
                {
                    bool campusAlreadyExists = false; // We asume the campus does not exist yet

                    campusQuery = db.Campus.Where(n => n.Name.Equals(monitorbeurt.Campus.Name));
                    foreach(var campus in campusQuery) //First check if the campus exists in the database
                    {
                        if (campus.Name == monitorbeurt.Campus.Name) {
                            monitorbeurt.Campus = campus;
                            campusAlreadyExists = true; 
                        }
                    }

                    if(!campusAlreadyExists)
                    {
                        foreach(var campus in campusLijst) // if the campus is not in the db check if it exists in our current uploaded list
                        {
                            if (campus.Name == monitorbeurt.Campus.Name) {
                                monitorbeurt.Campus = campus;
                                campusAlreadyExists = true; 
                            }
                        }
                    }

                    if (db.MonitorBeurt.Where(n => n.ExamenNaam.Equals(monitorbeurt.ExamenNaam)).Count().Equals(0))
                        db.MonitorBeurt.Add(monitorbeurt);

                    if(!campusAlreadyExists) // if the campus does not exist in the database nor the uploaded list then add it to our current list
                        campusLijst.Add(monitorbeurt.Campus);
                }
            }
            file.InputStream.Close();

            try { db.SaveChanges(); }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Debug.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Debug.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }

            return RedirectToAction("Index");
        }

        // GET: /MonitorBeurt/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            var reservatie = from m in db.Reservatie
                             where m.ToezichtbeurtId == id
                                 select m;
            ReservatieModel res = new ReservatieModel();
            MonitorBeurtModel monitorbeurtmodel = db.MonitorBeurt.Find(id);
            if (monitorbeurtmodel == null)
            {
                return HttpNotFound();
            }
            var tuple = new Tuple<MonitorBeurtModel,ReservatieModel,IEnumerable<ReservatieModel>>(monitorbeurtmodel, res,reservatie);
            return View(tuple);
        }

        public ActionResult Reserveren(int? id)
        {
            return View();
        }

        // GET: /MonitorBeurt/Create
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create()
        {
            ViewBag.CampusId = new SelectList(await db.Campus.ToListAsync(), "Id", "Name");
            return View();
        }

        // POST: /MonitorBeurt/Create
		// To protect from over posting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		// 
		// Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(MonitorBeurtModel monitorbeurtmodel, int CampusId)
        {
            if (ModelState.IsValid)
            {
                var CampusList = db.Campus.ToList().Where(campus => campus.Id == CampusId);
                monitorbeurtmodel.Campus = CampusList.First();
                db.MonitorBeurt.Add(monitorbeurtmodel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(monitorbeurtmodel);
        }

        // GET: /MonitorBeurt/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            ViewBag.CampusId = new SelectList(await db.Campus.ToListAsync(), "Id", "Name");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonitorBeurtModel monitorbeurtmodel = db.MonitorBeurt.Find(id);
            if (monitorbeurtmodel == null)
            {
                return HttpNotFound();
            }
            return View(monitorbeurtmodel);
        }

        // POST: /MonitorBeurt/Edit/5
		// To protect from over posting attacks, please enable the specific properties you want to bind to, for 

AspnetIdentitySample/Views/MonitorBeurt/Create.cshtml
@model Examonitor.Models.MonitorBeurtModel

@{
    ViewBag.Title = "Monitorbeurt Toevoegen";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal" })) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <legend>Toevoegen</legend>
    <form class="form-horizontal" role="form">

            <div class="col-sm-10">
                @Html.EditorFor(model => model.ExamenNaam)
            </div>

            <div class="col-sm-10">
                @Html.EditorFor(model => model.BeginDatum)
            </div>

            <div class="col-sm-10">
                @Html.EditorFor(model => model.EindDatum)
            </div>

            <div class="col-sm-10">
                @Html.EditorFor(model => model.Capaciteit)

            </div>

            <div class="col-sm-10">
                @Html.EditorFor(model => model.Digitaal)
            </div>

        <div class="col-sm-10">
            <div class="form-group">
                @Html.LabelFor(m => m.Campus, new { @class = "col-sm-2 control-label" })
                @Html.DropDownList("CampusId", ViewBag.CampusId as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Campus, null, new { @class = "help-block" })
            </div>
        </div>

        <div class="btn-group">
            <input type="submit" value="Toevoegen" class="btn btn-success btn-default" />
            <input type="BUTTON" value="Annuleren" class="btn btn-danger btn-default" onclick="window.location.href = '@Url.Action("Index")'" />
        </div>

</form>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $('#BeginDatum').datetimepicker();
        });
    </script>
    <script type="text/javascript">
        $(function () {
            $('#EindDatum').datetimepicker();
        });
    </script>
}

AspnetIdentitySample/Views/MonitorBeurt/Delete.cshtml
@model Examonitor.Models.MonitorBeurtModel

@{
    ViewBag.Title = "Delete";
}

<h2>Verwijderen van monitorbeurt</h2>

<h3>Ben jij zeker dat jij je monitorbeurt "@Html.DisplayFor(model => model.ExamenNaam)" wilt verwijderen?</h3>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

        <div class="btn-group">
            <input type="submit" value="Verwijderen" class="btn btn-success btn-default" />
            <input type="BUTTON" value="Annuleren" class="btn btn-danger btn-default" onclick="window.location.href = '@Url.Action("Index")'" />
        </div>
}

AspnetIdentitySample/Views/MonitorBeurt/DeleteAll.cshtml
@model Examonitor.Models.MonitorBeurtModel

@{
    ViewBag.Title = "Delete All";
}

<h2>Delete All</h2>

<h3>Are you sure you want to delete EVERYTHING?</h3>
<p>Enter <i>deleteall</i> in capital letters below to confirm action.</p>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-actions no-color">
        <input type="text" placeholder="Enter confirmation" name="confirmation" />
        <input type="submit" value="Delete" class="btn" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

AspnetIdentitySample/Views/MonitorBeurt/Details.cshtml
@using Examonitor.Models;
@model Tuple<MonitorBeurtModel, ReservatieModel, IEnumerable<ReservatieModel>>


@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>MonitorBeurt</legend>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.Item1.ExamenNaam)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Item1.ExamenNaam)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Item1.BeginDatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.BeginDatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item1.EindDatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.EindDatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item1.Duurtijd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.Duurtijd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item1.Capaciteit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.Capaciteit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item1.Gereserveerd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.Gereserveerd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item1.Digitaal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.Digitaal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item1.Campus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.Campus.Name)
        </dd>

    </dl>
</fieldset>
@if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("Admin"))
{<table class="table">
        <tr>
            <th width="1%">
                @Html.DisplayNameFor(model => model.Item2.UserName)
            </th>
        </tr>

        @foreach (var item in Model.Item3)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
            </tr>
        }
    </table>
}
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Item1.MonitorBeurtId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AspnetIdentitySample/Views/MonitorBeurt/Edit.cshtml
@model Examonitor.Models.MonitorBeurtModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.MonitorBeurtId)
    @Html.HiddenFor(model => model.Gereserveerd)

     <form class="form-horizontal" role="form">

            <div class="col-sm-10">
                @Html.EditorFor(model => model.ExamenNaam)
            </div>

            <div class="col-sm-10">
                @Html.EditorFor(model => model.BeginDatum)
            </div>

            <div class="col-sm-10">
                @Html.EditorFor(model => model.EindDatum)
            </div>

            <div class="col-sm-10">
                @Html.EditorFor(model => model.Capaciteit)

            </div>

            <div class="col-sm-10">
                @Html.EditorFor(model => model.Digitaal)
            </div>

        <div class="col-sm-10">
            <div class="form-group">
                @Html.LabelFor(m => m.Campus, new { @class = "col-sm-2 control-label" })
                @Html.DropDownList("CampusId", ViewBag.CampusId as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Campus, null, new { @class = "help-block" })
            </div>
        </div>

        <div class="btn-group">
            <input type="submit" value="Opslaan" class="btn btn-success btn-default" />
            <input type="BUTTON" value="Annuleren" class="btn btn-danger btn-default" onclick="window.location.href = '@Url.Action("Index")'" />
        </div>

</form>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $('#BeginDatum').datetimepicker();
        });
    </script>
    <script type="text/javascript">
        $(function () {
            $('#EindDatum').datetimepicker();
        });
    </script>
}

AspnetIdentitySample/Views/MonitorBeurt/Import.cshtml
@model Examonitor.Models.MonitorBeurtModel

@{
    ViewBag.Title = "Monitorbeurten importeren";
}

<h2>@ViewBag.Title</h2>

<p>Een json tekstbestand importeren.</p>
<p>Voorbeeld:<b>
    <pre>
{
	"monitorbeurten": [
		{
			"monitorbeurt": 
			{
			  "ExamenNaam": "Monitorbeurt 1",
			  "BeginDatum": "2013/10/18 08:00 AM",
			  "EindDatum": "2013/10/18 08:00 PM",
			  "Capaciteit": 10,
			  "Digitaal": false,
			  "Campus": "Campus 1"
			}
		},
		{
			"monitorbeurt": 
			{
			  "ExamenNaam": "Monitorbeurt 2",
			  "BeginDatum": "2013/10/18 08:00 AM",
			  "EindDatum": "2013/10/18 08:00 PM",
			  "Capaciteit": 20,
			  "Digitaal": true,
			  "Campus": "Campus 2"
			}
		}
	]
}
</pre>
    </b></p>
<p>Indien de campus niet bestaat zal deze aangemaakt worden.</p>
<p>TODO: testen schrijven (Exception handling) en de input van DateTime aanpassen zodat het nakkelijker is te exporteren/importeren</p>
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-horizontal col-sm-4">
        <div class="form-group">
            <input type="file" id="file" name="file" class="btn btn-success btn-sm" />
        </div>
    </div>
        <div class="form-group">
            <input type="submit" value="Importeren" class="btn btn-success btn-default" />
        </div>
   
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AspnetIdentitySample/Views/MonitorBeurt/Index.cshtml
@using Examonitor;
@model IEnumerable<Examonitor.Models.MonitorBeurtModel>
@Styles.Render("~/Content/Sites.css")  

@{
    ViewBag.Title = "Monitor Beurten";
}

<p>
    <h2>Monitor beurten</h2>

    @if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("Admin"))
    {
        @Html.ActionLink("Monitorbeurt toevoegen", "Create")
        <span> | </span>
        @Html.ActionLink("Monitorbeurten importeren", "Import")
        <span> | </span>
        @Html.ActionLink("Alles Verwijderen ", "DeleteAll")
    }
    <br /><br />
    @using (Html.BeginForm("Index", "MonitorBeurt", FormMethod.Get))
    {
        <div class="form-inline">
            Campus: @Html.Editor("MonitorBeurtCampus", ViewBag.CurrentFilter as string)
            <input type="submit" value="Zoeken" class="btn btn-success btn-sm" />
        </div>
    }
</p>
<table class="table">
    <tr>
        <th>
            
            @Html.ActionLink("Examen", "Index", new { sortOrder = ViewBag.ExamenNaamSortParm, MonitorBeurtCampus = ViewBag.CurrentFilter }, new { })
        </th>
        <th>
            @Html.ActionLink("Datum", "Index", new { sortOrder = ViewBag.DatumSortParm, MonitorBeurtCampus = ViewBag.CurrentFilter }, new { })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duurtijd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Capaciteit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gereserveerd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Digitaal)
        </th>
        <th>
            @Html.ActionLink("Campus", "Index", new { sortOrder = ViewBag.CampusSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @{var rowColor = "rgba(255,255,255,0.0);"; }
@foreach (var item in Model)
{
    if (item.ReservedByCurrentUser) { rowColor = "rgba(0,255,0,0.5)"; }
    else {
        if (!item.Available) { rowColor = "rgba(255,0,0,0.5)"; }
        else { rowColor = "rgba(255,255,255,0.0)"; }
    }
    
    <tr style="background-color:@rowColor;">
        <td>
            @Html.DisplayFor(modelItem => item.ExamenNaam)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BeginDatum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Duurtijd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Capaciteit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gereserveerd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Digitaal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Campus.Name)
        </td>
        <td>
            @if (User.IsInRole("Admin")) { @Html.Raw("<a href=\"" + @Url.Action("Edit", "Monitorbeurt", new { id = item.MonitorBeurtId }) + "\"><i class=\"glyphicon glyphicon-edit black\" title=\"Bewerken\"></i></a>"); }
            @if (User.IsInRole("Admin")) { @Html.Raw("<a href=\"" + @Url.Action("Delete", "Monitorbeurt", new { id = item.MonitorBeurtId }) + "\"><i class=\"glyphicon glyphicon-remove red\" title=\"Verwijderen\"></i></a>"); }
            @if (!item.ReservedByCurrentUser && item.Available) { @Html.Raw("<a href=\"" + @Url.Action("ReservatieToevoegen", "Reservatie", new { id = item.MonitorBeurtId }) + "\"><i class=\"glyphicon glyphicon-log-in\" title=\"Inschrijven\"></i></a>");}
            @if (item.ReservedByCurrentUser){ @Html.Raw("<a href=\"" + @Url.Action("Delete", "Reservatie", new { id = item.CurrentRegistratieID }) + "\"><i class=\"glyphicon glyphicon-log-out\" title=\"Uitschrijven\"></i></a>"); }
        </td>
    </tr>
}

</table>